### ISSUE TITLE
Question: How did you manage to make the mod compatible with multible versions at the same time?

### ISSUE THREAD

**Issue by NextRaven10** [NordAct/Leaf-Me-Alone#1]
Hello, I am a not so experienced Dev.
I would like to know how you managed to make your mod compatible with so many versions at the same time?
I have been struggling with this since the beginning :(

Thx in advance :)

PS:  Sorry for making a new Issue, I did´t see any other method of contacting you

**Comment by NordAct** [comment]
Np, I really didn't expect someone wanting to actually ask how I did it. Tho I happen to have plenty MC modding Discord servers on my list, including Fabric's one

Answer is simple: mod is just so small, code of used methods and classes, that were used in mod, didn't change between versions of Minecraft that were targeted. It's literally one mixin mod
